server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  application:
    name: myproject-app
  datasource:
    url: "jdbc:mysql://localhost:3306/db_weather_app"
    username: root
    password: root